version: '3.1'

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: cactus_core
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
