---
# DEFAULT CONFIGURATION
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  docker:
    compose:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: TRACE
---
# LOCAL CONFIGURATION
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}}/${DATABASE_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      file: ./compose.yml
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
